version: "3"
services:

  api:
    build: 
      context: .
      dockerfile: ./docker/go/Dockerfile
    working_dir: /app
    volumes:
      - ./backend/:/app
    env_file: ./docker/go/docker.env
    ports:
      - "8400:8080"
    tty: true

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "8401:3306"
    volumes:
      - ./var/mysql:/var/lib/mysql
    env_file: ./docker/mysql/docker.env
