// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChartsColumns holds the columns for the "charts" table.
	ChartsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "patch", Type: field.TypeBool, Default: false},
		{Name: "generation", Type: field.TypeInt, Default: 0},
		{Name: "gender", Type: field.TypeInt, Default: 0},
		{Name: "allergy", Type: field.TypeInt, Default: 0},
		{Name: "rash", Type: field.TypeInt, Default: 0},
		{Name: "sting", Type: field.TypeInt, Default: 0},
		{Name: "dye_when", Type: field.TypeInt, Default: 0},
		{Name: "dye_where", Type: field.TypeInt, Default: 0},
		{Name: "hena_when", Type: field.TypeInt, Default: 0},
		{Name: "rebonded_when", Type: field.TypeInt, Default: 0},
		{Name: "manicure_when", Type: field.TypeInt, Default: 0},
		{Name: "perm_when", Type: field.TypeInt, Default: 0},
		{Name: "treatment_when", Type: field.TypeInt, Default: 0},
		{Name: "notice_reason", Type: field.TypeInt, Default: 0},
		{Name: "last_name", Type: field.TypeString, Size: 2147483647},
		{Name: "first_name", Type: field.TypeString, Size: 2147483647},
		{Name: "last_name_hiragana", Type: field.TypeString, Size: 2147483647},
		{Name: "first_name_hiragana", Type: field.TypeString, Size: 2147483647},
		{Name: "postal_code", Type: field.TypeString, Size: 2147483647},
		{Name: "prefecture_id", Type: field.TypeInt, Default: 0},
		{Name: "address", Type: field.TypeString, Size: 2147483647},
		{Name: "tel", Type: field.TypeString, Size: 2147483647},
		{Name: "email", Type: field.TypeString, Size: 2147483647},
	}
	// ChartsTable holds the schema information for the "charts" table.
	ChartsTable = &schema.Table{
		Name:       "charts",
		Columns:    ChartsColumns,
		PrimaryKey: []*schema.Column{ChartsColumns[0]},
	}
	// StaffsColumns holds the columns for the "staffs" table.
	StaffsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"STAFF", "ADMIN"}, Default: "STAFF"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// StaffsTable holds the schema information for the "staffs" table.
	StaffsTable = &schema.Table{
		Name:       "staffs",
		Columns:    StaffsColumns,
		PrimaryKey: []*schema.Column{StaffsColumns[0]},
	}
	// TodosColumns holds the columns for the "todos" table.
	TodosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "text", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"IN_PROGRESS", "COMPLETED"}, Default: "IN_PROGRESS"},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "todo_parent", Type: field.TypeInt, Nullable: true},
	}
	// TodosTable holds the schema information for the "todos" table.
	TodosTable = &schema.Table{
		Name:       "todos",
		Columns:    TodosColumns,
		PrimaryKey: []*schema.Column{TodosColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "todos_todos_parent",
				Columns:    []*schema.Column{TodosColumns[5]},
				RefColumns: []*schema.Column{TodosColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChartsTable,
		StaffsTable,
		TodosTable,
	}
)

func init() {
	TodosTable.ForeignKeys[0].RefTable = TodosTable
}
