// Code generated by entc, DO NOT EDIT.

package chart

import (
	"time"
)

const (
	// Label holds the string label denoting the chart type in the database.
	Label = "chart"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldPatch holds the string denoting the patch field in the database.
	FieldPatch = "patch"
	// FieldGeneration holds the string denoting the generation field in the database.
	FieldGeneration = "generation"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldAllergy holds the string denoting the allergy field in the database.
	FieldAllergy = "allergy"
	// FieldRash holds the string denoting the rash field in the database.
	FieldRash = "rash"
	// FieldSting holds the string denoting the sting field in the database.
	FieldSting = "sting"
	// FieldDyeWhen holds the string denoting the dye_when field in the database.
	FieldDyeWhen = "dye_when"
	// FieldDyeWhere holds the string denoting the dye_where field in the database.
	FieldDyeWhere = "dye_where"
	// FieldHenaWhen holds the string denoting the hena_when field in the database.
	FieldHenaWhen = "hena_when"
	// FieldRebondedWhen holds the string denoting the rebonded_when field in the database.
	FieldRebondedWhen = "rebonded_when"
	// FieldManicureWhen holds the string denoting the manicure_when field in the database.
	FieldManicureWhen = "manicure_when"
	// FieldPermWhen holds the string denoting the perm_when field in the database.
	FieldPermWhen = "perm_when"
	// FieldTreatmentWhen holds the string denoting the treatment_when field in the database.
	FieldTreatmentWhen = "treatment_when"
	// FieldNoticeReason holds the string denoting the notice_reason field in the database.
	FieldNoticeReason = "notice_reason"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastNameHiragana holds the string denoting the last_name_hiragana field in the database.
	FieldLastNameHiragana = "last_name_hiragana"
	// FieldFirstNameHiragana holds the string denoting the first_name_hiragana field in the database.
	FieldFirstNameHiragana = "first_name_hiragana"
	// FieldPostalCode holds the string denoting the postal_code field in the database.
	FieldPostalCode = "postal_code"
	// FieldPrefectureID holds the string denoting the prefecture_id field in the database.
	FieldPrefectureID = "prefecture_id"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldTel holds the string denoting the tel field in the database.
	FieldTel = "tel"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// Table holds the table name of the chart in the database.
	Table = "charts"
)

// Columns holds all SQL columns for chart fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldPatch,
	FieldGeneration,
	FieldGender,
	FieldAllergy,
	FieldRash,
	FieldSting,
	FieldDyeWhen,
	FieldDyeWhere,
	FieldHenaWhen,
	FieldRebondedWhen,
	FieldManicureWhen,
	FieldPermWhen,
	FieldTreatmentWhen,
	FieldNoticeReason,
	FieldLastName,
	FieldFirstName,
	FieldLastNameHiragana,
	FieldFirstNameHiragana,
	FieldPostalCode,
	FieldPrefectureID,
	FieldAddress,
	FieldTel,
	FieldEmail,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultPatch holds the default value on creation for the "patch" field.
	DefaultPatch bool
	// DefaultGeneration holds the default value on creation for the "generation" field.
	DefaultGeneration int
	// DefaultGender holds the default value on creation for the "gender" field.
	DefaultGender int
	// DefaultAllergy holds the default value on creation for the "allergy" field.
	DefaultAllergy int
	// DefaultRash holds the default value on creation for the "rash" field.
	DefaultRash int
	// DefaultSting holds the default value on creation for the "sting" field.
	DefaultSting int
	// DefaultDyeWhen holds the default value on creation for the "dye_when" field.
	DefaultDyeWhen int
	// DefaultDyeWhere holds the default value on creation for the "dye_where" field.
	DefaultDyeWhere int
	// DefaultHenaWhen holds the default value on creation for the "hena_when" field.
	DefaultHenaWhen int
	// DefaultRebondedWhen holds the default value on creation for the "rebonded_when" field.
	DefaultRebondedWhen int
	// DefaultManicureWhen holds the default value on creation for the "manicure_when" field.
	DefaultManicureWhen int
	// DefaultPermWhen holds the default value on creation for the "perm_when" field.
	DefaultPermWhen int
	// DefaultTreatmentWhen holds the default value on creation for the "treatment_when" field.
	DefaultTreatmentWhen int
	// DefaultNoticeReason holds the default value on creation for the "notice_reason" field.
	DefaultNoticeReason int
	// LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	LastNameValidator func(string) error
	// FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	FirstNameValidator func(string) error
	// DefaultPrefectureID holds the default value on creation for the "prefecture_id" field.
	DefaultPrefectureID int
)
