import Head from 'next/head'
import Form from '../components/chart/Form'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <Form />
      </main>
    </div>
  )
}
